/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ApiPublicProductImageRouteImport } from './routes/api/public/product-image'
import { Route as ApiPublicSyncEstoqueRouteImport } from './routes/api/public/sync-estoque'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImageRoute = ApiPublicProductImageRouteImport.update({
  id: '/api/public/product-image',
  path: '/api/public/product-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncEstoqueRoute = ApiPublicSyncEstoqueRouteImport.update({
  id: '/api/public/sync-estoque',
  path: '/api/public/sync-estoque',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
  '/api/public/sync-estoque': typeof ApiPublicSyncEstoqueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
  '/api/public/sync-estoque': typeof ApiPublicSyncEstoqueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
  '/api/public/sync-estoque': typeof ApiPublicSyncEstoqueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/catalogo'
    | '/contato'
    | '/empresa'
    | '/api/public/product-image'
    | '/api/public/sync-estoque'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/catalogo'
    | '/contato'
    | '/empresa'
    | '/api/public/product-image'
    | '/api/public/sync-estoque'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/catalogo'
    | '/contato'
    | '/empresa'
    | '/api/public/product-image'
    | '/api/public/sync-estoque'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CatalogoRoute: typeof CatalogoRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  ApiPublicProductImageRoute: typeof ApiPublicProductImageRoute
  ApiPublicSyncEstoqueRoute: typeof ApiPublicSyncEstoqueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image': {
      id: '/api/public/product-image'
      path: '/api/public/product-image'
      fullPath: '/api/public/product-image'
      preLoaderRoute: typeof ApiPublicProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-estoque': {
      id: '/api/public/sync-estoque'
      path: '/api/public/sync-estoque'
      fullPath: '/api/public/sync-estoque'
      preLoaderRoute: typeof ApiPublicSyncEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CatalogoRoute: CatalogoRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  ApiPublicProductImageRoute: ApiPublicProductImageRoute,
  ApiPublicSyncEstoqueRoute: ApiPublicSyncEstoqueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
